
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      DB_HOST: db
      DB_NAME: event_mgmt
      DB_USER: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: event_mgmt
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
